### ISSUE TITLE
Not Scanning Bluetooth Devices

### ISSUE THREAD

**Issue by wataru-ew** [pogist/ForbiddenBluetooth#1]
Hi, 
When bluetooth switch is on from off, I confirm that the device's bluetooth is on.
Although I tried to scan bluetooth devices, It did not work.
NotificationName is always "BluetoothDiscoveryStateChangedNotification" not "BluetoothDeviceDiscoveredNotification".

Could you plz tell me why?
iOS version is 13.2.3.

**Comment by pogist** [comment]
Hey there, sorry for taking so long to answer you, I was a little out of github these last ~months~ days 😆 (just doing job stuff).

Anyways, this was happening because the scanning process was not getting reseted when switching between `on/off` states. For this reason `BluetoothManager` was not reissuing the devices it had already discovered, even when "powering" the manager off/on (I don't know why this happens).

But fortunately I get to fix this by calling `resetDeviceScanning` when starting the scanning process, see the [commit](https://github.com/pogist/ForbiddenBluetooth/commit/d3b4a2c9147d86a6446086f8d66001e082fe41fb).

**Comment by pogist** [comment]
Since the issue has been addressed I'm closing it. Also, thanks for pointing it out, I really appreciate the help.
